# -*- coding: utf-8 -*-
"""Topsis_102303650.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MY-wxkOydyk_e9dkEpdFQIv-JzKzv2NS
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile topsis.py
# import sys
# import os
# import pandas as pd
# import numpy as np
# 
# def error(msg):
#     print("Error:", msg)
#     sys.exit(1)
# 
# if len(sys.argv) != 5:
#     error("Correct number of parameters required:\n"
#           "inputFileName, Weights, Impacts, resultFileName")
# 
# input_file = sys.argv[1]
# weights = sys.argv[2].split(',')
# impacts = sys.argv[3].split(',')
# output_file = sys.argv[4]
# 
# if not os.path.exists(input_file):
#     error("File not Found")
# 
# try:
#     df = pd.read_csv(input_file)
# except:
#     error("Unable to read input file")
# 
# if df.shape[1] < 3:
#     error("The input file must contain three or more columns")
# 
# criteria = df.iloc[:, 1:]
# 
# try:
#     criteria = criteria.astype(float)
# except:
#     error("From 2nd to last columns must contain numeric values only")
# 
# if len(weights) != criteria.shape[1]:
#     error("The number of weights must be equal to number of criteria columns")
# 
# if len(impacts) != criteria.shape[1]:
#     error("The number of impacts must be equal to number of criteria columns")
# 
# try:
#     weights = np.array(weights, dtype=float)
# except:
#     error("Weights must be numeric and separated by comma")
# 
# for i in impacts:
#     if i not in ['+', '-']:
#         error("Impacts must be either +ve or -ve")
# 
# norm = criteria / np.sqrt((criteria ** 2).sum())
# 
# weighted = norm * weights
# ideal_best = []
# ideal_worst = []
# 
# for i in range(len(impacts)):
#     if impacts[i] == '+':
#         ideal_best.append(weighted.iloc[:, i].max())
#         ideal_worst.append(weighted.iloc[:, i].min())
#     else:
#         ideal_best.append(weighted.iloc[:, i].min())
#         ideal_worst.append(weighted.iloc[:, i].max())
# 
# ideal_best = np.array(ideal_best)
# ideal_worst = np.array(ideal_worst)
# 
# dist_best = np.sqrt(((weighted - ideal_best) ** 2).sum(axis=1))
# dist_worst = np.sqrt(((weighted - ideal_worst) ** 2).sum(axis=1))
# 
# score = dist_worst / (dist_best + dist_worst)
# 
# df["Topsis Score"] = (score * 100).round(2)
# df["Rank"] = df["Topsis Score"].rank(ascending=False).astype(int)
# 
# df.to_csv(output_file, index=False)
# 
# print("TOPSIS successfully executed")
#

!ls

import pandas as pd
pd.read_excel("data.xlsx").to_csv("input.csv", index=False)

!python topsis.py input.csv "0.25,0.25,0.25,0.25,0.25" "+,+,-,+,-" result.csv